In [9]:
import numpy as np

def sigmoid(x, derivative=False):
    if derivative:
        return x * (1 - x)
    else:
        ''' It returns 1/(1+exp(-x)). where the values lies between zero and one '''
        return 1/(1+np.exp(-x))
        
def RELU(x, derivative=False):
    if derivative:
        return np.where(x <= 0, 0, 1)
    else:
        ''' It returns zero if the input is less than zero otherwise it returns the given input. '''
        x1=[]
        for i in x:
            if i<0:
                x1.append(0)
            else:
                x1.append(i)
        return x1
    
def softmax(x, derivative=False):
    if derivative:
        return x * (1 - x)
    else:
        ''' Compute softmax values for each sets of scores in x. '''
        return np.exp(x) / np.sum(np.exp(x), axis=0)

In [10]:
class Layer:
    def __init__(self, input_size, output_size, activation):
        self.input_size = input_size
        self.output_size = output_size
        self.activation = activation

        self.weights = np.random.randn(self.input_size, self.output_size) * np.sqrt(2 / self.input_size)
        self.biases = np.zeros((1, self.output_size))

    def forward(self, inputs):
        result = (inputs @ self.weights) + self.biases
        result = self.activation(result)
        return result

    def backward(self, inputs, delta):
        # Calculate the derivative of the activation function
        derivative_activation = self.activation(inputs, derivative=True)

        # Calculate the error in this layer
        error = np.dot(delta, self.weights.T) * derivative_activation

        return error

In [11]:
def calculate_output_error(output, target):
        """Calculates the error in the output layer."""
        return output - target

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

X = np.array(X)

layer1 = Layer(4, 5, sigmoid)
layer2 = Layer(5, 3, sigmoid)
layer3 = Layer(3, 1, softmax)

In [12]:
layer1_output = layer1.forward(X)
print(layer1_output)

[[0.98723804 0.06289133 0.10754728 0.76892825 0.98558345]
 [0.51964357 0.53207272 0.01153945 0.19236734 0.88915034]
 [0.96925973 0.08180994 0.52244478 0.89532597 0.83327312]]


In [13]:
layer2_output = layer2.forward(layer1_output)
print(layer2_output)

[[0.17001934 0.4917039  0.40621342]
 [0.20119478 0.46033209 0.59288596]
 [0.16547137 0.46164041 0.37294871]]


In [14]:
output = layer3.forward(layer2_output)
print(output)

[[0.32584714]
 [0.37326768]
 [0.30088518]]


In [8]:
# calculate output error
output_error = calculate_output_error(output, 1)
print("output_error{}\n".format(output_error))

# calculate error in layer 3
layer3_error = layer3.backward(layer2_output, output_error)
print("layer3_error{}\n".format(layer3_error))

# calculate error in layer 2
layer2_error = layer2.backward(layer1_output, layer3_error)
print("layer2_error{}\n".format(layer2_error))

# calculate error in layer 1
layer1_error = layer1.backward(X, layer2_error)
print("layer1_error{}".format(layer1_error))

output_error[[-0.70063885]
 [-0.72849549]
 [-0.57086566]]

layer3_error[[-0.06246722  0.2276845   0.21246182]
 [-0.06422675  0.23622105  0.17979277]
 [-0.05044932  0.17782189  0.23138682]]

layer2_error[[ 0.12405314  0.01424578 -0.03413223 -0.0073753   0.01270878]
 [ 0.1168596   0.00025324 -0.00017234 -0.01343218  0.00026529]
 [ 0.10036245  0.0120244  -0.00147994  0.00019128  0.0026663 ]]

layer1_error[[ 0.         -0.00343605 -0.09321961  0.37491741]
 [-0.38189361  0.14875381 -0.10262646  0.2647172 ]
 [-0.65876107  0.03786641 -0.25648092  0.1408528 ]]
